### ISSUE TITLE
Finish matlab bindings for JOSS paper milestone

### ISSUE THREAD

**Issue by rubiop** [MeasureTransport/MParT#154]
Finish matlab bindings for JOSS paper milestone. As discussed in #149 this requires:

- [x] `MultiIndex`
- [x] `MultiIndexSet`  (to complete)
- [x] `ParameterizedFunctionBase`
- [x] `ConditionalMapBase`  (to complete)
- [x] `TriangularMap` (to complete)
- [x] `MapFactory`

**Comment by mparno** [comment]
Completed in #160
